# Generated by Django 3.2.11 on 2022-01-22 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_alter_chat_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='status',
            new_name='step',
        ),
    ]
