# Generated by Django 3.2.11 on 2022-01-23 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_alter_chat_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='step_in_process',
            field=models.BooleanField(default=False),
        ),
    ]
