# Generated by Django 3.2.11 on 2022-01-23 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_chat_step_in_process'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='step',
            field=models.CharField(default='PartingStep', max_length=150),
        ),
    ]
