# Generated by Django 3.2.11 on 2022-01-25 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0011_alter_chat_step'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatclient',
            name='email',
        ),
    ]
