# Generated by Django 3.2.11 on 2022-01-26 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0012_remove_chatclient_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatclient',
            name='has_contacts',
            field=models.BooleanField(default=False),
        ),
    ]
