# Generated by Django 3.2.8 on 2021-10-18 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.PositiveIntegerField(verbose_name='Jivo chat id')),
            ],
        ),
        migrations.CreateModel(
            name='ChatClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.PositiveIntegerField(verbose_name='Jivo client id')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Имя')),
                ('phone', models.CharField(blank=True, max_length=25, null=True, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Телефон')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot', models.BooleanField()),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.chat')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.chatclient')),
            ],
        ),
        migrations.AddField(
            model_name='chat',
            name='client_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.chatclient'),
        ),
    ]
