# Generated by Django 3.2.8 on 2021-10-19 10:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='selected_categories',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(verbose_name='category id'), default=list, size=None),
        ),
        migrations.AddField(
            model_name='chat',
            name='status',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='message',
            name='text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
